# Generated by Django 2.1.5 on 2019-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background_image',
            field=models.ImageField(upload_to='profile_backgrounds'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
