# Generated by Django 2.1.5 on 2019-04-01 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tag',
            new_name='InterestTag',
        ),
    ]
