# Generated by Django 2.1.5 on 2019-02-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match_site', '0002_auto_20190223_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_profile_pic', models.CharField(max_length=100)),
                ('profile_background_image', models.CharField(max_length=100)),
                ('profile_bio', models.CharField(max_length=200)),
                ('profile_education', models.CharField(max_length=100)),
                ('profile_interests', models.CharField(max_length=100)),
                ('profile_contact_info', models.CharField(max_length=100)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_site.user')),
            ],
        ),
    ]
