# Generated by Django 2.1.5 on 2019-02-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('role_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_join_date', models.DateTimeField(verbose_name='join date')),
                ('user_google_id', models.CharField(max_length=1000)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match_site.role')),
            ],
        ),
    ]
