# Generated by Django 2.1.5 on 2019-02-23 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('match_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
