# Generated by Django 2.1.5 on 2019-03-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match_site', '0002_auto_20190223_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='matchselection',
            name='user_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_matcher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchselection',
            name='user_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_matcher', to=settings.AUTH_USER_MODEL),
        ),
    ]
